// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace _5I_Marcatelli_Crossword.Migrations
{
    [DbContext(typeof(DbCruciverba))]
    partial class DbCruciverbaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Cruciverba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Solution")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SuggerimentoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SuggerimentoId");

                    b.ToTable("Cruciverba");
                });

            modelBuilder.Entity("Suggerimento", b =>
                {
                    b.Property<int>("SuggerimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descrizione")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isHoriz")
                        .HasColumnType("INTEGER");

                    b.HasKey("SuggerimentoId");

                    b.ToTable("Suggerimenti");
                });

            modelBuilder.Entity("Cruciverba", b =>
                {
                    b.HasOne("Suggerimento", "Suggerimento")
                        .WithMany("Cruciverbas")
                        .HasForeignKey("SuggerimentoId");

                    b.Navigation("Suggerimento");
                });

            modelBuilder.Entity("Suggerimento", b =>
                {
                    b.Navigation("Cruciverbas");
                });
#pragma warning restore 612, 618
        }
    }
}
